== sensehat_assist
RaspberryPi mounted SenseHat: helpers, assistance, general code

=== Necessary prerequisites
In order to run code, related to SenseHat, you'll:

- either have to have an actual SenseHat mounted on your computer - RaspberryPi + SenseHat,
- or must run an emulator.

==== Hardware
find detailed information here: https://www.raspberrypi.com/documentation/accessories/sense-hat.html

enter the following lines to install SenseHat: +
 
 sudo apt update
 sudo apt install sense-hat
 sudo reboot

==== Emulator
find detailed information here: https://sense-emu.readthedocs.io/en/v1.0/install.html

enter the following line to install the Emulator: +
(some parts may not be needed/working on specific systems)

 sudo apt-get install python-sense-emu python3-sense-emu sense-emu-tools

enter the following to uninstall it:

 sudo apt-get remove python-sense-emu python3-sense-emu sense-emu-tools

Also, for Ubuntu, the Emulator will not run due to numpy related errors. Correct these as shown on this
git - page.: https://github.com/astro-pi/python-sense-emu/pull/36/commits/6f0faa6a42ea60b88a4d617b1b6cf34a47768944

In short, you'll have to correct 3 python files of the emulator software:

* `humidity.py`
----
  -      self._humidities = np.full((10,), self._humidity, dtype=np.float)
  -      self._temperatures = np.full((31,), self._temperature, dtype=np.float)
  +      self._humidities = np.full((10,), self._humidity, dtype=float)
  +      self._temperatures = np.full((31,), self._temperature, dtype=float)
----

* `pressure.py`
----
  -  self._pressures = np.full((25,), self._pressure, dtype=np.float)
  -  self._temperatures = np.full((25,), self._temperature, dtype=np.float)
  +  self._pressures = np.full((25,), self._pressure, dtype=float)
  +  self._temperatures = np.full((25,), self._temperature, dtype=float)
----

* `imu.py`
----
  -      self._gyros = np.full((10, 3), self._gyro, dtype=np.float)
  -      self._accels = np.full((10, 3), self._accel, dtype=np.float)
  -      self._comps = np.full((10, 3), self._compass, dtype=np.float)
  +      self._gyros = np.full((10, 3), self._gyro, dtype=float)
  +      self._accels = np.full((10, 3), self._accel, dtype=float)
  +      self._comps = np.full((10, 3), self._compass, dtype=float)
----
